version: 2
jobs:
  build:
    environment:
      - MAVEN_OPTS: -Xmx2096m

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:
      - checkout

      - restore_cache:
          key: prestaclient-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - run: mvn package

      - save_cache:
          paths:
            - ~/.m2
          key: prestaclient-{{ checksum "pom.xml" }}